import React from 'react';

const ReportsView: React.FC = () => {
  return (
    <div className="page-content">
      <div className="section-header">
        <h1>System Reports</h1>
      </div>
      <div className="subtitle">
        Downloadable system-wide analytics and audit logs.
      </div>

      <div className="dashboard-grid">
        <div className="admin-card" style={{ gridColumn: 'span 12', padding: '4rem 2rem', textAlign: 'center', color: 'var(--c-text-tertiary)', borderStyle: 'dashed' }}>
          <div style={{ fontSize: '3rem', marginBottom: '1rem', opacity: 0.5 }}>📭</div>
          <div style={{ fontSize: '1.25rem', fontWeight: 600, color: 'var(--c-text-secondary)', marginBottom: '0.5rem' }}>No Reports Generated Yet</div>
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.875rem' }}>
            System audits and export files will appear here once generated by the admin triggers.
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportsView;